{
 "title": "Kubernetes / Addons / Fluentbit",
 "tags": [ "fluentbit" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(fluentbit_build_info, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fluentbit version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluentbit_build_info{pod=~\"$pod\"}",
     "legendFormat": "{{ version }}  "
    }
   ]
  },
  {
   "title": "Input bytes total (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod , name)",
     "legendFormat": "{{ pod }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Output bytes total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Input records total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Output records total (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total{pod=~\"$pod\"}[$__rate_interval])) by (pod, name)",
     "legendFormat": "{{ pod }} - {{ name }}"
    }
   ]
  },
  {
   "title": "Retries / Retries Failed (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_retries_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Retries "
    },
    {
     "expr": "sum(rate(fluentbit_output_retries_failed_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Retries Failed"
    }
   ]
  },
  {
   "title": "Output error (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}