{
 "title": "Kubernetes - Alerting",
 "tags": [
  "kubernetes",
  "alerting"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Kubernetes Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Health Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status!=\"false\", condition!=\"Ready\"}) by (node, condition)",
     "legendFormat": "{{ node }} - {{ condition }}"
    }
   ]
  },
  {
   "title": "Kubelet Node Config Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_node_config_error) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Kubernetes Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Daemonsets - Unavailable Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_unavailable) by (daemonset)",
     "legendFormat": "{{ daemonset }}"
    }
   ]
  },
  {
   "title": "Deployments - Unavailable Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable) by (deployment)",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Not bounded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase!=\"Bound\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes Claims - Not bounded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Capacity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_capacity_bytes) by (persistentvolumeclaim) /\nsum(kubelet_volume_stats_available_bytes) by (persistentvolumeclaim) - 1)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_inodes_used) by (persistentvolumeclaim)\n/ sum(kubelet_volume_stats_inodes_free + kubelet_volume_stats_inodes_used) by (persistentvolumeclaim)\n* 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Endpoints not ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_endpoint_address_not_ready) by (endpoint)",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  }
 ]
}